### ISSUE TITLE
My code only works to the half, so when i press dot two times it will show up as 0.. (In process of creating a calculator)

### ISSUE THREAD

**Issue by Petyanator** [WC-BrandenBent/WC-JS-Day2#2]
dot.addEventListener("click", function(){
    let numbers1 = mainText.textContent.split(" ")
    console.log(numbers1)
    if (numbers1[0] == ""){
        mainText.textContent = "0."
    } else{
        mainText.textContent += "."
    }
})

**Comment by WC-BrandenBent** [comment]
Testing
